"use server"

import { createClient } from "@/lib/supabase/server"
import { getVendorId } from "@/app/actions/vendors"


export async function getClients(vendorId?: number) {
  const supabase = await createClient()
  const id = vendorId ?? (await getVendorId())

  const { data, error } = await supabase
    .from("clients")
    .select("*")
    .eq("vendor_id", id)
    .order("name", { ascending: true })

  if (error) throw error

  return data
}

export async function getInvoices(vendorId?: number) {
  const supabase = await createClient()
  const id = vendorId ?? (await getVendorId())

  const { data, error } = await supabase
    .from("invoices")
    .select("*")
    .eq("vendor_id", id)
    .order("created_at", { ascending: false })

  if (error) throw error

  return data
}

export async function deleteInvoice(invoiceId: number) {
  const supabase = await createClient()
  const id = await getVendorId()

  const { error } = await supabase
    .from("invoices")
    .delete()
    .eq("id", invoiceId)
    .eq("vendor_id", id)

  if (error) throw error
}

export async function createInvoice(formData: {
  client_id?: number
  customer_name: string
  customer_email: string
  customer_phone?: string
  items: any[]
  subtotal: number
  tax_amount: number
  total_amount: number
  due_date?: string
}) {
  const supabase = await createClient()
  const id = await getVendorId()

  // Insert invoice and let the DB trigger generate invoice_number atomically
  const { data, error } = await supabase
    .from("invoices")
    .insert({
      vendor_id: id,
      client_id: formData.client_id || null,
      customer_name: formData.customer_name,
      customer_email: formData.customer_email,
      customer_phone: formData.customer_phone || null,
      items: formData.items,
      subtotal: formData.subtotal,
      tax_amount: formData.tax_amount,
      total_amount: formData.total_amount,
      due_date: formData.due_date || null,
    })
    .select()
    .single()

  if (error) throw error

  return data
}

export async function updateInvoice(invoiceId: number, formData: {
  client_id?: number
  customer_name: string
  customer_email: string
  customer_phone?: string
  items: any[]
  subtotal: number
  tax_amount: number
  total_amount: number
  due_date?: string
}) {
  const supabase = await createClient()
  const id = await getVendorId()

  const { data, error } = await supabase
    .from("invoices")
    .update({
      client_id: formData.client_id || null,
      customer_name: formData.customer_name,
      customer_email: formData.customer_email,
      customer_phone: formData.customer_phone || null,
      items: formData.items,
      subtotal: formData.subtotal,
      tax_amount: formData.tax_amount,
      total_amount: formData.total_amount,
      due_date: formData.due_date || null,
    })
    .eq("id", invoiceId)
    .eq("vendor_id", id)
    .select()
    .single()

  if (error) throw error

  return data
}

export async function markInvoiceAsPaid(invoiceId: number, paymentMethod?: string) {
  const supabase = await createClient()
  const id = await getVendorId()

  // Get the invoice details
  const { data: invoice, error: invoiceError } = await supabase
    .from("invoices")
    .select("*")
    .eq("id", invoiceId)
    .eq("vendor_id", id)
    .single()

  if (invoiceError || !invoice) throw new Error("Invoice not found")

  // Update invoice status
  const { error: updateError } = await supabase
    .from("invoices")
    .update({
      invoices_status: "paid",
      paid_at: new Date().toISOString(),
      receipt_generated: true
    })
    .eq("id", invoiceId)
    .eq("vendor_id", id)

  if (updateError) throw updateError

  // Ensure only one receipt per invoice: return existing if present
  const { data: existingReceipts } = await supabase
    .from("receipts")
    .select("*")
    .eq("invoice_id", invoiceId)
    .limit(1)

  if (existingReceipts && existingReceipts.length > 0) {
    return { invoice, receipt: existingReceipts[0] }
  }

  // Create receipt — receipt_number is generated by the DB trigger
  const { data: receipt, error: receiptError } = await supabase
    .from("receipts")
    .insert({
      vendor_id: id,
      invoice_id: invoiceId,
      client_id: invoice.client_id,
      customer_name: invoice.customer_name,
      customer_email: invoice.customer_email,
      customer_phone: invoice.customer_phone,
      items: invoice.items,
      subtotal: invoice.subtotal,
      tax_amount: invoice.tax_amount,
      total_amount: invoice.total_amount,
      amount_paid: invoice.total_amount,
      payment_method: paymentMethod || "bank_transfer",
      currency: invoice.currency,
      payment_date: new Date().toISOString(),
    })
    .select()
    .single()

  if (receiptError) throw receiptError

  return { invoice, receipt }
}

export async function getReceipts(vendorId?: number) {
  const supabase = await createClient()
  const id = vendorId ?? (await getVendorId())

  const { data, error } = await supabase
    .from("receipts")
    .select("*")
    .eq("vendor_id", id)
    .order("created_at", { ascending: false })

  if (error) throw error

  return data
}

export async function getCustomersWithInvoices(vendorId?: number) {
  const supabase = await createClient()
  const id = vendorId ?? (await getVendorId())

  // Get customers for this vendor
  const { data: customers, error } = await supabase
    .from("customers")
    .select("*")
    .eq("vendor_id", id)
    .order("name", { ascending: true })

  if (error) throw error

  // For each customer, we could potentially link to clients/invoices
  // but since there's no direct relationship, we'll return all customers
  // with placeholder stats for now
  const customersWithStats = customers.map(customer => ({
    ...customer,
    invoice_count: 0, // Placeholder - would need proper linking
    receipt_count: 0, // Placeholder - would need proper linking
    total_spent: 0,   // Placeholder - would need proper linking
  }))

  return customersWithStats
}